/** AUTO-GENERATED — do not edit by hand. Run: npx tsx scripts/generate-achievement-lucide-icons.mts */
import { Activity, Airplay, AlarmClock, Album, Anchor, Aperture, Archive, ArchiveRestore, Armchair, ArrowBigUp, ArrowLeftRight, Atom, Award, Axe, Backpack, Badge, BadgeCheck, Banknote, BarChart3, Bath, Battery, Beaker, Beer, Bell, Bike, Binary, Bird, Blocks, Bolt, Book, BookOpen, Bookmark, Bot, Box, Boxes, Brain, Brush, Building, Bus, Cake, Calculator, Calendar, CalendarCheck, CalendarCheck2, CalendarDays, CalendarHeart, CalendarRange, Camera, Car, Cast, CheckCheck, Circle, CircleCheckBig, CircleDot, CircleStop, Clock, CloudRain, Code, Coffee, Coins, Command, Compass, Construction, Contrast, Copy, Cpu, CreditCard, Crosshair, Crown, Database, Diamond, Dice5, Dices, Disc, Dog, DoorOpen, Droplet, Ear, Earth, Eclipse, Egg, Eye, Factory, FastForward, Feather, File, FileCheck, FileSpreadsheet, Film, Fingerprint, Flag, Flame, FlameKindling, FlipHorizontal, FlipVertical, Flower2, Folder, FolderPlus, Footprints, Forward, GalleryHorizontal, Gauge, Gem, Ghost, Gift, Glasses, Globe, GraduationCap, Grid2x2, Grid3x3, Hammer, HandMetal, Hash, Headphones, Heart, HeartCrack, HeartHandshake, Heater, History, Home, Hourglass, IceCreamCone, Image, Inbox, Infinity, Joystick, Kanban, Key, LampDesk, Landmark, Layers, Layers2, LayoutGrid, Medal, Milestone, Moon, MoonStar, Network, Package, Palette, PenLine, Percent, QrCode, Rainbow, RefreshCw, Repeat, RotateCcw, ScrollText, Shield, Skull, Sparkles, Star, Swords, Target, Timer, TrendingUp, Trophy, UserCheck, Users, Zap, type LucideIcon } from 'lucide-react'
import type { AchievementIconKind } from '@/lib/achievements'

const ICONS = {
  Activity,
  Airplay,
  AlarmClock,
  Album,
  Anchor,
  Aperture,
  Archive,
  ArchiveRestore,
  Armchair,
  ArrowBigUp,
  ArrowLeftRight,
  Atom,
  Award,
  Axe,
  Backpack,
  Badge,
  BadgeCheck,
  Banknote,
  BarChart3,
  Bath,
  Battery,
  Beaker,
  Beer,
  Bell,
  Bike,
  Binary,
  Bird,
  Blocks,
  Bolt,
  Book,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Boxes,
  Brain,
  Brush,
  Building,
  Bus,
  Cake,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarCheck2,
  CalendarDays,
  CalendarHeart,
  CalendarRange,
  Camera,
  Car,
  Cast,
  CheckCheck,
  Circle,
  CircleCheckBig,
  CircleDot,
  CircleStop,
  Clock,
  CloudRain,
  Code,
  Coffee,
  Coins,
  Command,
  Compass,
  Construction,
  Contrast,
  Copy,
  Cpu,
  CreditCard,
  Crosshair,
  Crown,
  Database,
  Diamond,
  Dice5,
  Dices,
  Disc,
  Dog,
  DoorOpen,
  Droplet,
  Ear,
  Earth,
  Eclipse,
  Egg,
  Eye,
  Factory,
  FastForward,
  Feather,
  File,
  FileCheck,
  FileSpreadsheet,
  Film,
  Fingerprint,
  Flag,
  Flame,
  FlameKindling,
  FlipHorizontal,
  FlipVertical,
  Flower2,
  Folder,
  FolderPlus,
  Footprints,
  Forward,
  GalleryHorizontal,
  Gauge,
  Gem,
  Ghost,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Grid2x2,
  Grid3x3,
  Hammer,
  HandMetal,
  Hash,
  Headphones,
  Heart,
  HeartCrack,
  HeartHandshake,
  Heater,
  History,
  Home,
  Hourglass,
  IceCreamCone,
  Image,
  Inbox,
  Infinity,
  Joystick,
  Kanban,
  Key,
  LampDesk,
  Landmark,
  Layers,
  Layers2,
  LayoutGrid,
  Medal,
  Milestone,
  Moon,
  MoonStar,
  Network,
  Package,
  Palette,
  PenLine,
  Percent,
  QrCode,
  Rainbow,
  RefreshCw,
  Repeat,
  RotateCcw,
  ScrollText,
  Shield,
  Skull,
  Sparkles,
  Star,
  Swords,
  Target,
  Timer,
  TrendingUp,
  Trophy,
  UserCheck,
  Users,
  Zap,
} as const satisfies Record<string, LucideIcon>

export const ACHIEVEMENT_LUCIDE_MAP: Record<string, keyof typeof ICONS> = {
  "achievement_hunter": 'Trophy',
  "alternating_fate": 'Activity',
  "balanced_rival": 'Airplay',
  "black_vs_yellow": 'AlarmClock',
  "blue_mastery": 'Album',
  "bounce_back": 'Anchor',
  "break_opp_streak": 'Aperture',
  "category_sweep": 'Archive',
  "centurion_wins": 'Medal',
  "chaos_session": 'ArchiveRestore',
  "christmas_clash": 'Armchair',
  "circle_session": 'ArrowBigUp',
  "clean_record": 'ArrowLeftRight',
  "clean_sweep": 'Atom',
  "closer": 'Axe',
  "clutch_finisher": 'Backpack',
  "clutch_streak": 'Badge',
  "cold_open": 'BadgeCheck',
  "color_clash_green_purple": 'Banknote',
  "color_clash_red_blue": 'BarChart3',
  "color_devotee": 'Bath',
  "color_spectrum": 'Palette',
  "comeback": 'RotateCcw',
  "completionist_90": 'Award',
  "counter_pick": 'Crosshair',
  "debut_redemption": 'Battery',
  "debut_win": 'Beaker',
  "deck_nomad": 'Bell',
  "deck_rotator": 'Beer',
  "deck_specialist": 'Layers',
  "dual_color_master": 'Binary',
  "dual_tone": 'Bike',
  "early_bird": 'Bird',
  "eb_specialist": 'Blocks',
  "exactly_fifty": 'Bolt',
  "first_player_king": 'Zap',
  "first_second_balance": 'Book',
  "first_win": 'Star',
  "flawless_table": 'BookOpen',
  "friday_night": 'Bookmark',
  "friendship_games": 'Bot',
  "gg_writer": 'Box',
  "giant_slayer": 'Shield',
  "green_mastery": 'Boxes',
  "group_anchor": 'Brain',
  "group_code_join": 'QrCode',
  "group_star": 'Users',
  "halloween_night": 'Brush',
  "history_keeper": 'History',
  "hot_day": 'Building',
  "hot_hand": 'Bus',
  "ice_breaker": 'Cake',
  "import_archivist": 'Calculator',
  "iron_win_rate": 'Percent',
  "leader_collector": 'GalleryHorizontal',
  "leader_loyalty": 'CalendarCheck',
  "leader_rotation": 'CalendarCheck2',
  "leap_day": 'CalendarDays',
  "loss_survivor": 'CalendarHeart',
  "loyalist": 'CalendarRange',
  "lucky_seven": 'Camera',
  "lunch_break": 'Coffee',
  "marathon_mind": 'Car',
  "marathon_month": 'Cast',
  "match_100": 'CheckCheck',
  "match_1000": 'CircleCheckBig',
  "match_500": 'CircleDot',
  "match_777": 'CircleStop',
  "meta_breaker": 'Hammer',
  "meta_explorer": 'Compass',
  "meta_rebel": 'Clock',
  "meta_sheep": 'CloudRain',
  "midnight_duel": 'MoonStar',
  "mirror_master": 'Copy',
  "mono_maniac": 'Circle',
  "mono_session": 'Code',
  "nemesis_70": 'Coins',
  "nemesis_bond": 'Command',
  "nemesis_slayer": 'Construction',
  "new_face_welcomer": 'Contrast',
  "new_session_starter": 'Cpu',
  "new_year_first": 'CreditCard',
  "night_owl": 'Database',
  "no_mercy": 'Dice5',
  "note_poet": 'PenLine',
  "onboarding_graduate": 'Dices',
  "one_session_five_unlock": 'Diamond',
  "op_era": 'DoorOpen',
  "op16_native": 'Disc',
  "opening_act": 'Droplet',
  "palindrome_score": 'Ear',
  "perfect_session": 'Crown',
  "perfect_week": 'Earth',
  "prime_hunter": 'Eclipse',
  "profile_linked": 'UserCheck',
  "purple_mastery": 'Egg',
  "rainbow_pilot": 'Eye',
  "rainbow_session": 'Rainbow',
  "red_mastery": 'Factory',
  "rematch_king": 'Repeat',
  "revenge_win": 'Skull',
  "rival_bond": 'Swords',
  "rival_respect": 'FastForward',
  "rival_top5": 'Feather',
  "rivalry_sweep": 'File',
  "roster_full": 'FileCheck',
  "round_robin": 'Network',
  "same_day_skill_triple": 'FileSpreadsheet',
  "second_player_king": 'Film',
  "second_striker": 'Target',
  "secret_achievement_hunter": 'Fingerprint',
  "secret_all_dash": 'Flag',
  "secret_handshake": 'FlipHorizontal',
  "secret_lucky_roll": 'FlipVertical',
  "secret_midnight_mirror": 'Flower2',
  "secret_zero_note_streak": 'Folder',
  "session_archive": 'FolderPlus',
  "session_closer_5": 'Footprints',
  "session_end_ritual": 'Forward',
  "session_heater": 'Gauge',
  "session_marathon": 'Timer',
  "session_opener_5": 'Gem',
  "set_collector": 'Package',
  "set_dominance": 'Ghost',
  "set_hopper": 'Gift',
  "single_color_session_sweep": 'Glasses',
  "single_table_night": 'Globe',
  "skill_trifecta": 'GraduationCap',
  "slot_one_legend": 'Grid2x2',
  "slot_wanderer": 'Grid3x3',
  "speed_demon": 'HandMetal',
  "st_deck_winner": 'Hash',
  "store_regular": 'Headphones',
  "streak_legend": 'FlameKindling',
  "streak_saver": 'Heart',
  "summer_surge": 'HeartCrack',
  "sunday_league": 'HeartHandshake',
  "table_tactician": 'Heater',
  "table_veteran": 'LayoutGrid',
  "tri_color_trouble": 'Home',
  "tricolor_win": 'Hourglass',
  "trio_triumph": 'IceCreamCone',
  "turn_hunter": 'Image',
  "underdog": 'Dog',
  "upset_alarm": 'TrendingUp',
  "upset_chain": 'Inbox',
  "veteran": 'ScrollText',
  "weekday_grind": 'Infinity',
  "weekend_warrior": 'Calendar',
  "weekly_grinder": 'Joystick',
  "weighted_progress_100": 'Kanban',
  "weighted_progress_50": 'Key',
  "white_mastery": 'LampDesk',
  "win_250": 'Landmark',
  "win_or_learn": 'Layers2',
  "win_streak": 'Flame',
}

const KIND_FALLBACK: Record<AchievementIconKind, keyof typeof ICONS> = {
  medal: 'Medal',
  flame: 'Flame',
  cards: 'Layers',
  compass: 'Compass',
  package: 'Package',
  swords: 'Swords',
  crown: 'Crown',
  palette: 'Palette',
  bolt: 'Zap',
  star: 'Star',
  anchor: 'Anchor',
  trophy: 'Trophy',
  moon: 'Moon',
  sparkles: 'Sparkles',
  shield: 'Shield',
  refresh: 'RefreshCw',
}

const CATEGORY_FALLBACK: Record<string, keyof typeof ICONS> = {
  milestone: 'Milestone',
  streak: 'Flame',
  skill: 'Crosshair',
  meta: 'Compass',
  social: 'Users',
  fun: 'Sparkles',
}

export function resolveAchievementLucideIcon(
  achievementId: string,
  kind?: AchievementIconKind,
  category?: string,
): LucideIcon {
  const key =
    ACHIEVEMENT_LUCIDE_MAP[achievementId] ??
    (kind ? KIND_FALLBACK[kind] : undefined) ??
    CATEGORY_FALLBACK[category ?? 'milestone'] ??
    'Star'
  return ICONS[key as keyof typeof ICONS] ?? ICONS.Star
}
